---

build:
  image: node:20
  stage: build
  cache:
    paths:
      - node_modules/
  variables:
    VUE_APP_PROJECT_URL: $CI_PROJECT_URL
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  needs:
    - build
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public/
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
