import { tostring } from '../utils/c'

//
// Map level types.
// The following data structures define the persistent format
// used in the lumps of the WAD files.
//

// Lump order in a map WAD: each map needs a couple of lumps
// to provide a complete scene geometry description.
export const enum MapLumpOrder {
  // A separator, name, ExMx or MAPxx
  Label,
  // Monsters, items..
  Things,
  // LineDefs, from editing
  LineDefs,
  // SideDefs, from editing
  SideDefs,
  // Vertices, edited and BSP splits generated
  Vertexes,
  // LineSegs, from LineDefs split by BSP
  Segs,
  // SubSectors, list of LineSegs
  SSectors,
  // BSP nodes
  Nodes,
  // Sectors, from editing
  Sectors,
  // LUT, sector-sector visibility
  Reject,
  // LUT, motion clipping, walls/grid element
  BlockMap
}

// A SideDef, defining the visual appearance of a wall,
// by setting textures and offsets.
export class MapSideDef {
  static sizeOf = 2 + 2 + 8 + 8 + 8 + 2

  textureOffset: number
  rowOffset: number
  topTexture: string
  bottomTexture: string
  midTexture: string

  // Front sector, towards viewer.
  sector: number

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 15)
    this.textureOffset = int16[0]
    this.rowOffset = int16[1]
    this.topTexture = tostring(buffer, 4, 8)
    this.bottomTexture = tostring(buffer, 12, 8)
    this.midTexture = tostring(buffer, 20, 8)

    this.sector = int16[14]
  }
}

// A LineDef, as used for editing, and as input
// to the BSP builder.
export class MapLineDef {
  static sizeOf = 2 * 5 + 2 * 2

  v1: number
  v2: number
  flags: number
  special: number
  tag: number

  // sidenum[1] will be -1 if one sided
  sideNum: number[]

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 7)
    this.v1 = int16[0]
    this.v2 = int16[1]
    this.flags = int16[2]
    this.special = int16[3]
    this.tag = int16[4]

    this.sideNum = [ int16[5], int16[6] ]
  }
}

//
// LineDef attributes.
//
export const enum MapLineFlag {
  // Solid, is an obstacle.
  Blocking = 1,

  // Blocks monsters only.
  BlockMonsters = 2,

  // Backside will not be present at all
  //  if not two sided.
  TwoSided = 4,

  // If a texture is pegged, the texture will have
  // the end exposed to air held constant at the
  // top or bottom of the texture (stairs or pulled
  // down things) and will move with a height change
  // of one of the neighbor sectors.
  // Unpegged textures allways have the first row of
  // the texture at the top pixel of the line for both
  // top and bottom textures (use next to windows).

  // upper texture unpegged
  DontPegTop = 8,

  // lower texture unpegged
  DontPegBottom = 16,

  // In AutoMap: don't map as two sided: IT'S A SECRET!
  Secret = 32,

  // Sound rendering: don't let sound cross two of these.
  SoundBlock = 64,

  // Don't draw on the automap at all.
  DontDraw = 128,

  // Set if already seen, thus drawn in automap.
  Mapped = 256,

}

// Sector definition, from editing.
export class MapSector {
  static sizeOf = 2 + 2 + 8 + 8 + 2 + 2 + 2

  floorHeight: number
  ceilingHeight: number
  floorPic: string
  ceilingPic: string
  lightLevel: number
  special: number
  tag: number

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 13)

    this.floorHeight = int16[0]
    this.ceilingHeight = int16[1]
    this.floorPic = tostring(buffer, 4, 8)
    this.ceilingPic = tostring(buffer, 12, 8)
    this.lightLevel = int16[10]
    this.special = int16[11]
    this.tag = int16[12]
  }
}

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
export class MapSeg {
  static sizeOf = 2 * 6

  v1: number
  v2: number
  angle: number
  lineDef: number
  side: number
  offset: number

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 6)

    this.v1 = int16[0]
    this.v2 = int16[1]
    this.angle = int16[2]
    this.lineDef = int16[3]
    this.side = int16[4]
    this.offset = int16[5]
  }
}

// BSP node structure.

// Indicate a leaf.
export const NF_SUBSECTOR = 0x8000

// Indicate a leaf.
export class MapNode {
  static sizeOf = 2 + 2 + 2 + 2 + 2 * 4 * 2 + 2 * 2

  // Partition line from (x,y) to x+dx,y+dy)
  x: number
  y: number
  dX: number
  dY: number

  // Bounding box for each child,
  // clip against view frustum.
  bbox: number[][]

  // If NF_SUBSECTOR its a subsector,
  // else it's a node of another subtree.
  children: number[]

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 12)
    const uint16 = new Uint16Array(buffer, 24, 2)

    this.x = int16[0]
    this.y = int16[1]
    this.dX = int16[2]
    this.dY = int16[3]
    this.bbox = [
      [ int16[4], int16[5], int16[6], int16[7] ],
      [ int16[8], int16[9], int16[10], int16[11] ],
    ]
    this.children = [ uint16[0], uint16[1] ]
  }
}
