import { FRACUNIT } from '../../misc/fixed'
import { MObjFlag } from '../../play/mobj/mobj-flag'
import { MObjInfo } from './mobj-info'
import { SfxName } from '../sounds/sfx-name'
import { StateNum } from './state-num'

export const mObjInfos = [
  // MT_PLAYER
  new MObjInfo(
    -1,
    StateNum.Play,
    100,
    StateNum.PlayRun1,
    SfxName.None,
    0,
    SfxName.None,
    StateNum.PlayPain,
    255,
    SfxName.Plpain,
    StateNum.Null,
    StateNum.PlayAtk1,
    StateNum.PlayDie1,
    StateNum.PlayXdie1,
    SfxName.Pldeth,
    0,
    16 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.DropOff | MObjFlag.PickUp | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_POSSESSED
  new MObjInfo(
    3004,
    StateNum.PossStnd,
    20,
    StateNum.PossRun1,
    SfxName.Posit1,
    8,
    SfxName.Pistol,
    StateNum.PossPain,
    200,
    SfxName.Popain,
    0,
    StateNum.PossAtk1,
    StateNum.PossDie1,
    StateNum.PossXdie1,
    SfxName.Podth1,
    8,
    20 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.Posact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.PossRaise1),

  // MT_SHOTGUY
  new MObjInfo(
    9,
    StateNum.SposStnd,
    30,
    StateNum.SposRun1,
    SfxName.Posit2,
    8,
    0,
    StateNum.SposPain,
    170,
    SfxName.Popain,
    0,
    StateNum.SposAtk1,
    StateNum.SposDie1,
    StateNum.SposXdie1,
    SfxName.Podth2,
    8,
    20 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.Posact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.SposRaise1),

  // MT_VILE
  new MObjInfo(
    64,
    StateNum.VileStnd,
    700,
    StateNum.VileRun1,
    SfxName.Vilsit,
    8,
    0,
    StateNum.VilePain,
    10,
    SfxName.Vipain,
    0,
    StateNum.VileAtk1,
    StateNum.VileDie1,
    StateNum.Null,
    SfxName.Vildth,
    15,
    20 * FRACUNIT,
    56 * FRACUNIT,
    500,
    0,
    SfxName.Vilact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.Null),

  // MT_FIRE
  new MObjInfo(
    -1,
    StateNum.Fire1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_UNDEAD
  new MObjInfo(
    66,
    StateNum.SkelStnd,
    300,
    StateNum.SkelRun1,
    SfxName.Skesit,
    8,
    0,
    StateNum.SkelPain,
    100,
    SfxName.Popain,
    StateNum.SkelFist1,
    StateNum.SkelMiss1,
    StateNum.SkelDie1,
    StateNum.Null,
    SfxName.Skedth,
    10,
    20 * FRACUNIT,
    56 * FRACUNIT,
    500,
    0,
    SfxName.Skeact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.SkelRaise1),

  // MT_TRACER
  new MObjInfo(
    -1,
    StateNum.Tracer,
    1000,
    StateNum.Null,
    SfxName.Skeatk,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Traceexp1,
    StateNum.Null,
    SfxName.Barexp,
    10 * FRACUNIT,
    11 * FRACUNIT,
    8 * FRACUNIT,
    100,
    10,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_SMOKE
  new MObjInfo(
    -1,
    StateNum.Smoke1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_FATSO
  new MObjInfo(
    67,
    StateNum.FattStnd,
    600,
    StateNum.FattRun1,
    SfxName.Mansit,
    8,
    0,
    StateNum.FattPain,
    80,
    SfxName.Mnpain,
    0,
    StateNum.FattAtk1,
    StateNum.FattDie1,
    StateNum.Null,
    SfxName.Mandth,
    8,
    48 * FRACUNIT,
    64 * FRACUNIT,
    1000,
    0,
    SfxName.Posact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.FattRaise1),

  // MT_FATSHOT
  new MObjInfo(
    -1,
    StateNum.Fatshot1,
    1000,
    StateNum.Null,
    SfxName.Firsht,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Fatshotx1,
    StateNum.Null,
    SfxName.Firxpl,
    20 * FRACUNIT,
    6 * FRACUNIT,
    8 * FRACUNIT,
    100,
    8,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_CHAINGUY
  new MObjInfo(
    65,
    StateNum.CposStnd,
    70,
    StateNum.CposRun1,
    SfxName.Posit2,
    8,
    0,
    StateNum.CposPain,
    170,
    SfxName.Popain,
    0,
    StateNum.CposAtk1,
    StateNum.CposDie1,
    StateNum.CposXdie1,
    SfxName.Podth2,
    8,
    20 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.Posact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.CposRaise1),

  // MT_TROOP
  new MObjInfo(
    3001,
    StateNum.TrooStnd,
    60,
    StateNum.TrooRun1,
    SfxName.Bgsit1,
    8,
    0,
    StateNum.TrooPain,
    200,
    SfxName.Popain,
    StateNum.TrooAtk1,
    StateNum.TrooAtk1,
    StateNum.TrooDie1,
    StateNum.TrooXdie1,
    SfxName.Bgdth1,
    8,
    20 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.Bgact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.TrooRaise1),

  // MT_SERGEANT
  new MObjInfo(
    3002,
    StateNum.SargStnd,
    150,
    StateNum.SargRun1,
    SfxName.Sgtsit,
    8,
    SfxName.Sgtatk,
    StateNum.SargPain,
    180,
    SfxName.Dmpain,
    StateNum.SargAtk1,
    0,
    StateNum.SargDie1,
    StateNum.Null,
    SfxName.Sgtdth,
    10,
    30 * FRACUNIT,
    56 * FRACUNIT,
    400,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.SargRaise1),

  // MT_SHADOWS
  new MObjInfo(
    58,
    StateNum.SargStnd,
    150,
    StateNum.SargRun1,
    SfxName.Sgtsit,
    8,
    SfxName.Sgtatk,
    StateNum.SargPain,
    180,
    SfxName.Dmpain,
    StateNum.SargAtk1,
    0,
    StateNum.SargDie1,
    StateNum.Null,
    SfxName.Sgtdth,
    10,
    30 * FRACUNIT,
    56 * FRACUNIT,
    400,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.Shadow | MObjFlag.CountKill,
    StateNum.SargRaise1),

  // MT_HEAD
  new MObjInfo(
    3005,
    StateNum.HeadStnd,
    400,
    StateNum.HeadRun1,
    SfxName.Cacsit,
    8,
    0,
    StateNum.HeadPain,
    128,
    SfxName.Dmpain,
    0,
    StateNum.HeadAtk1,
    StateNum.HeadDie1,
    StateNum.Null,
    SfxName.Cacdth,
    8,
    31 * FRACUNIT,
    56 * FRACUNIT,
    400,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.Float | MObjFlag.NoGravity | MObjFlag.CountKill,
    StateNum.HeadRaise1),

  // MT_BRUISER
  new MObjInfo(
    3003,
    StateNum.BossStnd,
    1000,
    StateNum.BossRun1,
    SfxName.Brssit,
    8,
    0,
    StateNum.BossPain,
    50,
    SfxName.Dmpain,
    StateNum.BossAtk1,
    StateNum.BossAtk1,
    StateNum.BossDie1,
    StateNum.Null,
    SfxName.Brsdth,
    8,
    24 * FRACUNIT,
    64 * FRACUNIT,
    1000,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.BossRaise1),

  // MT_BRUISERSHOT
  new MObjInfo(
    -1,
    StateNum.Brball1,
    1000,
    StateNum.Null,
    SfxName.Firsht,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Brballx1,
    StateNum.Null,
    SfxName.Firxpl,
    15 * FRACUNIT,
    6 * FRACUNIT,
    8 * FRACUNIT,
    100,
    8,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_KNIGHT
  new MObjInfo(
    69,
    StateNum.Bos2Stnd,
    500,
    StateNum.Bos2Run1,
    SfxName.Kntsit,
    8,
    0,
    StateNum.Bos2Pain,
    50,
    SfxName.Dmpain,
    StateNum.Bos2Atk1,
    StateNum.Bos2Atk1,
    StateNum.Bos2Die1,
    StateNum.Null,
    SfxName.Kntdth,
    8,
    24 * FRACUNIT,
    64 * FRACUNIT,
    1000,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.Bos2Raise1),

  // MT_SKULL
  new MObjInfo(
    3006,
    StateNum.SkullStnd,
    100,
    StateNum.SkullRun1,
    0,
    8,
    SfxName.Sklatk,
    StateNum.SkullPain,
    256,
    SfxName.Dmpain,
    0,
    StateNum.SkullAtk1,
    StateNum.SkullDie1,
    StateNum.Null,
    SfxName.Firxpl,
    8,
    16 * FRACUNIT,
    56 * FRACUNIT,
    50,
    3,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.Float | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_SPIDER
  new MObjInfo(
    7,
    StateNum.SpidStnd,
    3000,
    StateNum.SpidRun1,
    SfxName.Spisit,
    8,
    SfxName.Shotgn,
    StateNum.SpidPain,
    40,
    SfxName.Dmpain,
    0,
    StateNum.SpidAtk1,
    StateNum.SpidDie1,
    StateNum.Null,
    SfxName.Spidth,
    12,
    128 * FRACUNIT,
    100 * FRACUNIT,
    1000,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.Null),

  // MT_BABY
  new MObjInfo(
    68,
    StateNum.BspiStnd,
    500,
    StateNum.BspiSight,
    SfxName.Bspsit,
    8,
    0,
    StateNum.BspiPain,
    128,
    SfxName.Dmpain,
    0,
    StateNum.BspiAtk1,
    StateNum.BspiDie1,
    StateNum.Null,
    SfxName.Bspdth,
    12,
    64 * FRACUNIT,
    64 * FRACUNIT,
    600,
    0,
    SfxName.Bspact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.BspiRaise1),

  // MT_CYBORG
  new MObjInfo(
    16,
    StateNum.CyberStnd,
    4000,
    StateNum.CyberRun1,
    SfxName.Cybsit,
    8,
    0,
    StateNum.CyberPain,
    20,
    SfxName.Dmpain,
    0,
    StateNum.CyberAtk1,
    StateNum.CyberDie1,
    StateNum.Null,
    SfxName.Cybdth,
    16,
    40 * FRACUNIT,
    110 * FRACUNIT,
    1000,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.Null),

  // MT_PAIN
  new MObjInfo(
    71,
    StateNum.PainStnd,
    400,
    StateNum.PainRun1,
    SfxName.Pesit,
    8,
    0,
    StateNum.PainPain,
    128,
    SfxName.Pepain,
    0,
    StateNum.PainAtk1,
    StateNum.PainDie1,
    StateNum.Null,
    SfxName.Pedth,
    8,
    31 * FRACUNIT,
    56 * FRACUNIT,
    400,
    0,
    SfxName.Dmact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.Float | MObjFlag.NoGravity | MObjFlag.CountKill,
    StateNum.PainRaise1),

  // MT_WOLFSS
  new MObjInfo(
    84,
    StateNum.SswvStnd,
    50,
    StateNum.SswvRun1,
    SfxName.Sssit,
    8,
    0,
    StateNum.SswvPain,
    170,
    SfxName.Popain,
    0,
    StateNum.SswvAtk1,
    StateNum.SswvDie1,
    StateNum.SswvXdie1,
    SfxName.Ssdth,
    8,
    20 * FRACUNIT,
    56 * FRACUNIT,
    100,
    0,
    SfxName.Posact,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.SswvRaise1),

  // MT_KEEN
  new MObjInfo(
    72,
    StateNum.Keenstnd,
    100,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Keenpain,
    256,
    SfxName.Keenpn,
    StateNum.Null,
    StateNum.Null,
    StateNum.Commkeen,
    StateNum.Null,
    SfxName.Keendt,
    0,
    16 * FRACUNIT,
    72 * FRACUNIT,
    10000000,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity | MObjFlag.Shootable | MObjFlag.CountKill,
    StateNum.Null),

  // MT_BOSSBRAIN
  new MObjInfo(
    88,
    StateNum.Brain,
    250,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.BrainPain,
    255,
    SfxName.Bospn,
    StateNum.Null,
    StateNum.Null,
    StateNum.BrainDie1,
    StateNum.Null,
    SfxName.Bosdth,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    10000000,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.Shootable,
    StateNum.Null),

  // MT_BOSSSPIT
  new MObjInfo(
    89,
    StateNum.Braineye,
    1000,
    StateNum.Braineyesee,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    32 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoSector,
    StateNum.Null),

  // MT_BOSSTARGET
  new MObjInfo(
    87,
    StateNum.Null,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    32 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoSector,
    StateNum.Null),

  // MT_SPAWNSHOT
  new MObjInfo(
    -1,
    StateNum.Spawn1,
    1000,
    StateNum.Null,
    SfxName.Bospit,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.Firxpl,
    10 * FRACUNIT,
    6 * FRACUNIT,
    32 * FRACUNIT,
    100,
    3,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity | MObjFlag.NoClip,
    StateNum.Null),

  // MT_SPAWNFIRE
  new MObjInfo(
    -1,
    StateNum.Spawnfire1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_BARREL
  new MObjInfo(
    2035,
    StateNum.Bar1,
    20,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Bexp,
    StateNum.Null,
    SfxName.Barexp,
    0,
    10 * FRACUNIT,
    42 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.Shootable | MObjFlag.NoBlood,
    StateNum.Null),

  // MT_TROOPSHOT
  new MObjInfo(
    -1,
    StateNum.Tball1,
    1000,
    StateNum.Null,
    SfxName.Firsht,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Tballx1,
    StateNum.Null,
    SfxName.Firxpl,
    10 * FRACUNIT,
    6 * FRACUNIT,
    8 * FRACUNIT,
    100,
    3,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_HEADSHOT
  new MObjInfo(
    -1,
    StateNum.Rball1,
    1000,
    StateNum.Null,
    SfxName.Firsht,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Rballx1,
    StateNum.Null,
    SfxName.Firxpl,
    10 * FRACUNIT,
    6 * FRACUNIT,
    8 * FRACUNIT,
    100,
    5,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_ROCKET
  new MObjInfo(
    -1,
    StateNum.Rocket,
    1000,
    StateNum.Null,
    SfxName.Rlaunc,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Explode1,
    StateNum.Null,
    SfxName.Barexp,
    20 * FRACUNIT,
    11 * FRACUNIT,
    8 * FRACUNIT,
    100,
    20,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_PLASMA
  new MObjInfo(
    -1,
    StateNum.Plasball,
    1000,
    StateNum.Null,
    SfxName.Plasma,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Plasexp,
    StateNum.Null,
    SfxName.Firxpl,
    25 * FRACUNIT,
    13 * FRACUNIT,
    8 * FRACUNIT,
    100,
    5,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_BFG
  new MObjInfo(
    -1,
    StateNum.Bfgshot,
    1000,
    StateNum.Null,
    0,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Bfgland,
    StateNum.Null,
    SfxName.Rxplod,
    25 * FRACUNIT,
    13 * FRACUNIT,
    8 * FRACUNIT,
    100,
    100,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_ARACHPLAZ
  new MObjInfo(
    -1,
    StateNum.ArachPlaz,
    1000,
    StateNum.Null,
    SfxName.Plasma,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.ArachPlex,
    StateNum.Null,
    SfxName.Firxpl,
    25 * FRACUNIT,
    13 * FRACUNIT,
    8 * FRACUNIT,
    100,
    5,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.Missile | MObjFlag.DropOff | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_PUFF
  new MObjInfo(
    -1,
    StateNum.Puff1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_BLOOD
  new MObjInfo(
    -1,
    StateNum.Blood1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap,
    StateNum.Null),

  // MT_TFOG
  new MObjInfo(
    -1,
    StateNum.Tfog,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_IFOG
  new MObjInfo(
    -1,
    StateNum.Ifog,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_TELEPORTMAN
  new MObjInfo(
    14,
    StateNum.Null,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoSector,
    StateNum.Null),

  // MT_EXTRABFG
  new MObjInfo(
    -1,
    StateNum.Bfgexp,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC0
  new MObjInfo(
    2018,
    StateNum.Arm1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC1
  new MObjInfo(
    2019,
    StateNum.Arm2,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC2
  new MObjInfo(
    2014,
    StateNum.Bon1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MISC3
  new MObjInfo(
    2015,
    StateNum.Bon2,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MISC4
  new MObjInfo(
    5,
    StateNum.Bkey,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC5
  new MObjInfo(
    13,
    StateNum.Rkey,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC6
  new MObjInfo(
    6,
    StateNum.Ykey,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC7
  new MObjInfo(
    39,
    StateNum.Yskull,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC8
  new MObjInfo(
    38,
    StateNum.Rskull,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC9
  new MObjInfo(
    40,
    StateNum.Bskull,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.NotDMatch,
    StateNum.Null),

  // MT_MISC10
  new MObjInfo(
    2011,
    StateNum.Stim,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC11
  new MObjInfo(
    2012,
    StateNum.Medi,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC12
  new MObjInfo(
    2013,
    StateNum.Soul,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_INV
  new MObjInfo(
    2022,
    StateNum.Pinv,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MISC13
  new MObjInfo(
    2023,
    StateNum.Pstr,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_INS
  new MObjInfo(
    2024,
    StateNum.Pins,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MISC14
  new MObjInfo(
    2025,
    StateNum.Suit,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC15
  new MObjInfo(
    2026,
    StateNum.Pmap,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MISC16
  new MObjInfo(
    2045,
    StateNum.Pvis,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_MEGA
  new MObjInfo(
    83,
    StateNum.Mega,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special | MObjFlag.CountItem,
    StateNum.Null),

  // MT_CLIP
  new MObjInfo(
    2007,
    StateNum.Clip,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC17
  new MObjInfo(
    2048,
    StateNum.Ammo,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC18
  new MObjInfo(
    2010,
    StateNum.Rock,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC19
  new MObjInfo(
    2046,
    StateNum.Brok,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC20
  new MObjInfo(
    2047,
    StateNum.Cell,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC21
  new MObjInfo(
    17,
    StateNum.Celp,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC22
  new MObjInfo(
    2008,
    StateNum.Shel,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC23
  new MObjInfo(
    2049,
    StateNum.Sbox,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC24
  new MObjInfo(
    8,
    StateNum.Bpak,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC25
  new MObjInfo(
    2006,
    StateNum.Bfug,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_CHAINGUN
  new MObjInfo(
    2002,
    StateNum.Mgun,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC26
  new MObjInfo(
    2005,
    StateNum.Csaw,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC27
  new MObjInfo(
    2003,
    StateNum.Laun,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC28
  new MObjInfo(
    2004,
    StateNum.Plas,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_SHOTGUN
  new MObjInfo(
    2001,
    StateNum.Shot,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_SUPERSHOTGUN
  new MObjInfo(
    82,
    StateNum.Shot2,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Special,
    StateNum.Null),

  // MT_MISC29
  new MObjInfo(
    85,
    StateNum.Techlamp,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC30
  new MObjInfo(
    86,
    StateNum.Tech2lamp,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC31
  new MObjInfo(
    2028,
    StateNum.Colu,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC32
  new MObjInfo(
    30,
    StateNum.Tallgrncol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC33
  new MObjInfo(
    31,
    StateNum.Shrtgrncol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC34
  new MObjInfo(
    32,
    StateNum.Tallredcol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC35
  new MObjInfo(
    33,
    StateNum.Shrtredcol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC36
  new MObjInfo(
    37,
    StateNum.Skullcol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC37
  new MObjInfo(
    36,
    StateNum.Heartcol,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC38
  new MObjInfo(
    41,
    StateNum.Evileye,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC39
  new MObjInfo(
    42,
    StateNum.Floatskull,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC40
  new MObjInfo(
    43,
    StateNum.Torchtree,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC41
  new MObjInfo(
    44,
    StateNum.Bluetorch,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC42
  new MObjInfo(
    45,
    StateNum.Greentorch,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC43
  new MObjInfo(
    46,
    StateNum.Redtorch,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC44
  new MObjInfo(
    55,
    StateNum.Btorchshrt,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC45
  new MObjInfo(
    56,
    StateNum.Gtorchshrt,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC46
  new MObjInfo(
    57,
    StateNum.Rtorchshrt,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC47
  new MObjInfo(
    47,
    StateNum.Stalagtite,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC48
  new MObjInfo(
    48,
    StateNum.Techpillar,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC49
  new MObjInfo(
    34,
    StateNum.Candlestik,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC50
  new MObjInfo(
    35,
    StateNum.Candelabra,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC51
  new MObjInfo(
    49,
    StateNum.Bloodytwitch,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    68 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC52
  new MObjInfo(
    50,
    StateNum.Meat2,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    84 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC53
  new MObjInfo(
    51,
    StateNum.Meat3,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    84 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC54
  new MObjInfo(
    52,
    StateNum.Meat4,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    68 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC55
  new MObjInfo(
    53,
    StateNum.Meat5,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    52 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC56
  new MObjInfo(
    59,
    StateNum.Meat2,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    84 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC57
  new MObjInfo(
    60,
    StateNum.Meat4,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    68 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC58
  new MObjInfo(
    61,
    StateNum.Meat3,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    52 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC59
  new MObjInfo(
    62,
    StateNum.Meat5,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    52 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC60
  new MObjInfo(
    63,
    StateNum.Bloodytwitch,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    68 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC61
  new MObjInfo(
    22,
    StateNum.HeadDie6,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC62
  new MObjInfo(
    15,
    StateNum.PlayDie7,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC63
  new MObjInfo(
    18,
    StateNum.PossDie5,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC64
  new MObjInfo(
    21,
    StateNum.SargDie6,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC65
  new MObjInfo(
    23,
    StateNum.SkullDie6,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC66
  new MObjInfo(
    20,
    StateNum.TrooDie5,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC67
  new MObjInfo(
    19,
    StateNum.SposDie5,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC68
  new MObjInfo(
    10,
    StateNum.PlayXdie9,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC69
  new MObjInfo(
    12,
    StateNum.PlayXdie9,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC70
  new MObjInfo(
    28,
    StateNum.Headsonstick,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC71
  new MObjInfo(
    24,
    StateNum.Gibs,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    0,
    StateNum.Null),

  // MT_MISC72
  new MObjInfo(
    27,
    StateNum.Headonastick,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC73
  new MObjInfo(
    29,
    StateNum.Headcandles,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC74
  new MObjInfo(
    25,
    StateNum.Deadstick,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC75
  new MObjInfo(
    26,
    StateNum.Livestick,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC76
  new MObjInfo(
    54,
    StateNum.Bigtree,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    32 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC77
  new MObjInfo(
    70,
    StateNum.Bbar1,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid,
    StateNum.Null),

  // MT_MISC78
  new MObjInfo(
    73,
    StateNum.Hangnoguts,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    88 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC79
  new MObjInfo(
    74,
    StateNum.Hangbnobrain,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    88 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC80
  new MObjInfo(
    75,
    StateNum.Hangtlookdn,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    64 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC81
  new MObjInfo(
    76,
    StateNum.Hangtskull,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    64 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC82
  new MObjInfo(
    77,
    StateNum.Hangtlookup,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    64 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC83
  new MObjInfo(
    78,
    StateNum.Hangtnobrain,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    16 * FRACUNIT,
    64 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.Solid | MObjFlag.SpawnCeiling | MObjFlag.NoGravity,
    StateNum.Null),

  // MT_MISC84
  new MObjInfo(
    79,
    StateNum.Colongibs,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap,
    StateNum.Null),

  // MT_MISC85
  new MObjInfo(
    80,
    StateNum.Smallpool,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap,
    StateNum.Null),

  // MT_MISC86
  new MObjInfo(
    81,
    StateNum.Brainstem,
    1000,
    StateNum.Null,
    SfxName.None,
    8,
    SfxName.None,
    StateNum.Null,
    0,
    SfxName.None,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    StateNum.Null,
    SfxName.None,
    0,
    20 * FRACUNIT,
    16 * FRACUNIT,
    100,
    0,
    SfxName.None,
    MObjFlag.NoBlockMap,
    StateNum.Null),
]
