import { Line } from '../rendering/defs/line'
import { LumpType } from '../wad/lump'
import { MapLineFlag } from '../doom/data'
import { Seg } from '../rendering/segs/seg'
import { Side } from '../rendering/defs/side'
import { Vertex } from '../rendering/data/vertex'

export class SegArray extends Array<MapSeg> {
  static type: LumpType = 'segs'
  static isType(_: ArrayBuffer, name: string): boolean {
    return name === 'SEGS'
  }
  static get [Symbol.species](): ArrayConstructor {
    return Array
  }

  constructor(buffer: ArrayBuffer) {
    const numSegs = buffer.byteLength / MapSeg.sizeOf
    if (numSegs !== Math.floor(numSegs)) {
      throw 'invalid length of segs'
    }

    super(numSegs)

    for (let i = 0, msPtr = 0;
      i < numSegs;
      ++i, msPtr += MapSeg.sizeOf
    ) {
      this[i] = new MapSeg(buffer.slice(msPtr))
    }
  }

  getSegs(
    vertexes: readonly Vertex[],
    lines: readonly Line[],
    sides: readonly Side[],
  ): Seg[] {
    return this.map(s => {
      // new Seg(s, vertexes, lines, sides),
      const lineDef = lines[s.lineDef]
      const side = sides[lineDef.sideNum[s.side]]
      let backSide: Side | null = null
      if (lineDef.flags & MapLineFlag.TwoSided) {
        backSide = sides[lineDef.sideNum[s.side ^ 1]]
      }
      return new Seg(
        vertexes[s.v1],
        vertexes[s.v2],
        s.offset << 16,
        s.angle << 16 >>> 0,
        side,
        lineDef,
        side.sector,
        backSide ? backSide.sector : null,
      )
    })
  }

}

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
class MapSeg {
  static sizeOf = 2 * 6

  v1: number
  v2: number
  angle: number
  lineDef: number
  side: number
  offset: number

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 6)

    this.v1 = int16[0]
    this.v2 = int16[1]
    this.angle = int16[2]
    this.lineDef = int16[3]
    this.side = int16[4]
    this.offset = int16[5]
  }
}
