import { LumpType } from '../wad/lump'
import { SubSector } from '../rendering/defs/sub-sector'

export class SubSectorArray extends Array<MapSubSector> {
  static type: LumpType = 'sub-sectors'
  static isType(_: ArrayBuffer, name: string): boolean {
    return name === 'SSECTORS'
  }
  static get [Symbol.species](): ArrayConstructor {
    return Array
  }

  constructor(buffer: ArrayBuffer) {
    const numSubSectors = buffer.byteLength / MapSubSector.sizeOf
    if (numSubSectors !== Math.floor(numSubSectors)) {
      throw 'invalid length of sub-sectors'
    }

    super(numSubSectors)

    for (let i = 0, msPtr = 0;
      i < numSubSectors;
      ++i, msPtr += MapSubSector.sizeOf
    ) {
      this[i] = new MapSubSector(buffer.slice(msPtr))
    }
  }

  getSubSectors(): SubSector[] {
    return this.map(({ numSegs, firstSeg }) =>
      new SubSector(numSegs, firstSeg),
    )
  }

}

// SubSector, as generated by BSP.
class MapSubSector {
  static sizeOf = 2 + 2

  numSegs: number
  // Index of first one, segs are stored sequentially.
  firstSeg: number

  constructor(buffer: ArrayBuffer) {
    const int16 = new Int16Array(buffer, 0, 2)

    this.numSegs = int16[0]
    this.firstSeg = int16[1]
  }
}
