import { DEvent, GameAction, MAX_EVENTS } from './event'
import { GameMission, GameMode, GameState, Language, Skill, VERSION } from '../global/doomdef'
import { EnglishStrings } from '../translation/english'
import { FrenchStrings } from '../translation/french'
import { Game } from '../game/game'
import { HeadsUp } from '../heads-up/stuff'
import { Video as IVideo } from '../interfaces/video'
import { Menu } from '../menu/menu'
import { Params } from './params'
import { Play } from '../play/setup'
import { Video as RVIdeo } from '../rendering/video'
import { Rendering } from '../rendering/rendering'
import { Strings } from '../translation/strings'
import { Wad } from '../wad/wad'

async function access(file: string): Promise<boolean> {
  return (await fetch(file)).ok
}

export class Doom {

  // Game Mode - identify IWAD as shareware, retail etc.
  gameMode: GameMode = GameMode.Indetermined
  gameMission: GameMission = GameMission.Doom

  // Language
  language: Language = Language.English
  strings: Strings = new EnglishStrings()

  // Set if homebrew PWAD stuff has been added.
  modifiedGame = false

  private startSkill: Skill = -1
  private startEpisode = -1
  private startMap = -1
  private autoStart = false

  private advancedemo = false

  private wadfiles: string[] = []

  // started game with -devparm
  private devParam = false
  // checkparm of -nomonsters
  noMonsters = false
  // checkparm of -respawn
  respawnParam = false
  // checkparm of -fast
  fastParam = false

  // print title for every printed line
  private title = ''

  public wad = new Wad()
  private headsUp = new HeadsUp(this.wad)
  private rendering = new Rendering(this)
  public play = new Play(this, this.wad, this.rendering)
  game = new Game(this, this.rendering, this.play)
  private rvideo = new RVIdeo()
  private ivideo = new IVideo(this, this.rvideo)
  private menu = new Menu(this,
    this.headsUp,
    this.ivideo,
    this.rvideo,
    this.rendering,
    this.wad,
    this.game,
  )

  //
  // EVENT HANDLING
  //
  // Events are asynchronous inputs generally generated by the game user.
  // Events can be discarded if no responder claims them
  //
  private events = new Array<DEvent>(MAX_EVENTS)
  private eventHead = 0
  private eventTail = 0

  //
  // D_PostEvent
  // Called by the I/O functions when input is detected
  //
  postEvent(ev: DEvent): void {
    this.events[this.eventHead] = ev
    this.eventHead = ++this.eventHead & MAX_EVENTS - 1
  }

  //
  // D_ProcessEvents
  // Send all the events of the given timestamp down the responder chain
  //
  async processEvents(): Promise<void> {
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if (this.gameMode === GameMode.Commercial &&
        this.wad.checkNumForName('map01') < 0) {
      return
    }

    let ev: DEvent
    for (; this.eventTail !== this.eventHead;
      this.eventTail = ++this.eventTail & MAX_EVENTS - 1
    ) {
      ev = this.events[this.eventTail]
      if (await this.menu.responder(ev)) {
        // menu ate the event
        continue
      }
    }
  }

  // wipegamestate can be set to -1 to force a wipe on the next draw
  wipeGameState = GameState.DemoScreen
  private oldGameState: GameState = -1
  private borderDrawCount = 0
  //
  // D_Display
  //  draw current display, possibly wiping it from the previous
  //
  private async display(): Promise<void> {
    let wipe: boolean

    // change the view size if needed
    if (this.rendering.setSizeNeeded) {
      this.rendering.executeSetViewSize()
      // force background redraw
      this.oldGameState = -1
      this.borderDrawCount = 3
    }

    // save the current screen if about to wipe
    if (this.game.gameState !== this.wipeGameState) {
      wipe = true
    } else {
      wipe = false
    }

    // do buffered drawing
    switch (this.game.gameState) {
    case GameState.DemoScreen:
      await this.pageDrawer()
      break
    }

    // draw the view directly
    if (this.game.gameState === GameState.Level &&
    /* !this.autoMapActive &&  */this.game.gametic
    ) {
      this.rendering.renderPlayerView(
        this.game.players[this.game.displayPlayer],
      )
    }

    // clean up border stuff
    if (this.game.gameState !== this.oldGameState &&
        this.game.gameState !== GameState.Level) {
      this.ivideo.setPalette(await this.wad.cacheLumpName('PLAYPAL'))
    }

    this.oldGameState = this.wipeGameState = this.game.gameState

    // menus go directly to the screen
    // menu is drawn even on top of everything
    await this.menu.drawer()

    // normal update
    if (!wipe) {
      // page flip or blit buffer
      this.ivideo.finishUpdate()
      return
    }
  }

  //
  // D-DoomLoop()
  // Not a globally visible function,
  //  just included for source reference,
  //  called by D_DoomMain, never exits.
  // Manages timing and IO,
  //  calls all ?_Responder, ?_Ticker, and ?_Drawer,
  //  calls I_GetTime, I_StartFrame, and I_StartTic
  //
  private async doomLoop(): Promise<void> {
    this.ivideo.initGraphics()

    const w = async() => {
      // process one or more tics
      if (true) {
        this.ivideo.startTic()
        await this.processEvents()
        if (this.advancedemo) {
          this.doAdvanceDemo()
        }
        this.menu.ticker()
        this.game.gametic++
      }
      await this.display()
      requestAnimationFrame(w.bind(this))
    }
    await w()
  }

  //
  //  DEMO LOOP
  //
  private demoSequence = -1
  private pageTic = -1
  private pageName = ''

  //
  // D_PageTicker
  // Handles timing for warped projection
  //
  private pageTicker(): void {
    if (--this.pageTic < 0) {
      this.advanceDemo()
    }
  }

  //
  // D_PageDrawer
  //
  private async pageDrawer(): Promise<void> {
    this.rvideo.drawPatch(0, 0, 0,
      await this.wad.cacheLumpName(this.pageName),
    )
  }

  //
  // D_AdvanceDemo
  // Called after each demo or intro demosequence finishes
  //
  private advanceDemo(): void {
    this.advancedemo = true
  }

  //
  // This cycles through the demo sequences.
  // FIXME - version dependend demo numbers?
  //
  private doAdvanceDemo(): void {
    this.advancedemo = false
    this.game.gameAction = GameAction.Nothing

    if (this.gameMode === GameMode.Retail) {
      this.demoSequence = (this.demoSequence + 1) % 7
    } else {
      this.demoSequence = (this.demoSequence + 1) % 6
    }

    switch (this.demoSequence) {
    case 0:
      if (this.gameMode === GameMode.Commercial) {
        this.pageTic = 35 * 11
      } else {
        this.pageTic = 170
      }
      this.game.gameState = GameState.DemoScreen
      this.pageName = 'TITLEPIC'
      break
    case 1:
      // TODO
      break
    case 2:
      this.pageTic = 200
      this.game.gameState = GameState.DemoScreen
      this.pageName = 'CREDIT'
      break
    case 3:
      // TODO
      break
    case 4:
      this.game.gameState = GameState.DemoScreen
      if (this.gameMode === GameMode.Commercial) {
        this.pageTic = 35 * 11
        this.pageName = 'TITLEPIC'
      } else {
        this.pageTic = 200

        if (this.gameMode === GameMode.Retail) {
          this.pageName = 'CREDIT'
        } else {
          this.pageName = 'HELP2'
        }
      }
      break
    case 5:
      // TODO
      break
    case 6:
      // THE DEFINITIVE DOOM Special Edition demo
      // TODO
      break
    }
  }

  //
  // D_StartTitle
  //
  startTitle(): void {
    this.game.gameAction = GameAction.Nothing
    this.demoSequence = -1
    this.advanceDemo()
  }

  //
  // D_AddFile
  //
  private addFile(file: string) {
    this.wadfiles.push(file)
  }

  //
  // IdentifyVersion
  // Checks availability of IWAD files by name,
  // to determine whether registered/commercial features
  // should be executed (notably loading PWAD's).
  //
  private async identifyVersion(): Promise<void> {
    const doomWadDir = './data'
    // Commercial.
    const doom2wad = `${doomWadDir}/doom2.wad`

    // Retail.
    const doomuwad = `${doomWadDir}/doomu.wad`

    // Registered.
    const doomwad = `${doomWadDir}/doom.wad`

    // Shareware.
    const doom1wad = `${doomWadDir}/doom1.wad`

    const plutoniawad = `${doomWadDir}/plutonia.wad`

    const tntwad = `${doomWadDir}/tnt.wad`

    // French stuff.
    const doom2fwad = `${doomWadDir}/doom2f.wad`

    if (await access(doom2fwad)) {
      this.gameMode = GameMode.Commercial
      // C'est ridicule!
      // Let's handle languages in config files, okay?
      this.language = Language.French
      this.strings = new FrenchStrings()
      console.log('French version')
      this.addFile(doom2fwad)
      return
    }
    if (await access(doom2wad)) {
      this.gameMode = GameMode.Commercial
      this.addFile(doom2wad)
      return
    }
    if (await access(plutoniawad)) {
      this.gameMode = GameMode.Commercial
      this.addFile(plutoniawad)
      return
    }
    if (await access(tntwad)) {
      this.gameMode = GameMode.Commercial
      this.addFile(tntwad)
      return
    }
    if (await access(doomuwad)) {
      this.gameMode = GameMode.Retail
      this.addFile(doomuwad)
      return
    }
    if (await access(doomwad)) {
      this.gameMode = GameMode.Registered
      this.addFile(doomwad)
      return
    }
    if (await access(doom1wad)) {
      this.gameMode = GameMode.Shareware
      this.addFile(doom1wad)
      return
    }

    console.log('Game mode indeterminate')
    this.gameMode = GameMode.Indetermined

    // We don't abort. Let's see what the PWAD contains.
  }

  async init(param: Params): Promise<void> {
    await this.identifyVersion()

    this.noMonsters = !!param.noMonsters
    this.respawnParam = !!param.respawm
    this.fastParam = !!param.fast
    this.devParam = !!param.dev

    switch (this.gameMode) {
    case GameMode.Retail:
      this.title = '                         ' +
        `The Ultimate DOOM Startup v${Math.floor(VERSION / 100)}.${VERSION % 100}` +
        '                           '
      break
    case GameMode.Shareware:
      this.title = '                            ' +
        `DOOM Shareware Startup v${Math.floor(VERSION / 100)}.${VERSION % 100}` +
        '                           '
      break
    case GameMode.Registered:
      this.title = '                            ' +
        `DOOM Registered Startup v${Math.floor(VERSION / 100)}.${VERSION % 100}` +
        '                           '
      break
    case GameMode.Commercial:
      this.title = '                         ' +
        `DOOM 2: Hell on Earth v${Math.floor(VERSION / 100)}.${VERSION % 100}` +
        '                           '
      break
    default:
      this.title = '                     ' +
        `Public DOOM - v${Math.floor(VERSION / 100)}.${VERSION % 100}` +
        '                           '
      break
    }

    console.log(this.title)

    if (this.devParam) {
      console.log(this.strings.dDevstr)
    }

    // get skill / episode / map from parms
    this.startSkill = Skill.Medium
    this.startEpisode = 1
    this.startMap = 1
    this.autoStart = false

    if (param.skill !== undefined) {
      this.startSkill = param.skill
      this.autoStart = true
    }
    if (param.episode !== undefined) {
      this.startEpisode = param.episode
      this.autoStart = true
    }
    if (param.map !== undefined) {
      this.startMap = param.map
      this.autoStart = true
    }

    // init subsystems
    console.log('V_Init: allocate screens.')
    this.rvideo.init()

    console.log('W_Init: Init WADfiles.')
    await this.wad.initMultipleFiles(this.wadfiles)

    // Check and print which version is executed.
    switch (this.gameMode) {
    case GameMode.Shareware:
    case GameMode.Indetermined:
      console.log('===========================================================================')
      console.log('                                Shareware!')
      console.log('===========================================================================')
      break
    case GameMode.Registered:
    case GameMode.Retail:
    case GameMode.Commercial:
      console.log('===========================================================================')
      console.log('                 Commercial product - do not distribute!')
      console.log('         Please report software piracy to the SPA: 1-800-388-PIR8')
      console.log('===========================================================================')
      break
    default:
      // Ouch.
      break
    }

    console.log('M_Init: Init miscellaneous info.')
    this.menu.init()

    console.log('R_Init: Init DOOM refresh daemon - ')
    await this.rendering.init()

    console.log('P_Init: Init Playloop state.')
    this.play.init()

    console.log('HU_Init: Setting up heads up display.')
    await this.headsUp.init()

    if (this.game.gameAction !== GameAction.LoadGame) {
      if (this.autoStart) {
        await this.game.initNew(
          this.startSkill, this.startEpisode, this.startMap,
        )
      } else {
        // start up intro loop
        this.startTitle()
      }
    }

    await this.doomLoop()
  }
}

